In [1]:
import numpy as np 

In [2]:
x = np.arange(1,11)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
y = np.arange(11, 21)

print(y)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
x+y

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
3*x

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [6]:
x+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
x**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
import math as ma

# sin cos

round(ma.sin(ma.pi), 2)

0.0

$$x = (1,2,3)$$

$$sin(x) = (sin(1), sin(2), sin(3))$$

$$exp(x) = (e^1 , e^2, e^3)$$

In [11]:
X = np.arange(-2*np.pi, 2*np.pi + np.pi, np.pi )

print(X)

[-6.28318531 -3.14159265  0.          3.14159265  6.28318531]


In [12]:
np.sin(X)

array([ 2.4492936e-16, -1.2246468e-16,  0.0000000e+00,  1.2246468e-16,
       -2.4492936e-16])

In [13]:
np.cos(X)

array([ 1., -1.,  1., -1.,  1.])

In [16]:
print(x.ndim) #Dimensión del arreglo
print(x.size) #Tamaño del arreglo
print(x.shape) #(M, N) 

1
10
(10,)


# Álgebra lineal

$$\vec{x} = (1,2)$$

$$\vec{y} = (3,4)$$

## Producto interno


$$\vec{x} \cdot \vec{y} = 1 \cdot 3 + 2 \cdot 4$$

In [17]:
x = np.array([1,2])
y = np.array([3,4])

x.dot(y)   # x * y  -> y x

11

In [20]:
w = np.array([1,2,3])
z = np.array([4,5,6])

print(np.cross(w, z))

[-3  6 -3]



$$x + 2y = 5$$
$$3x + 4y = 6$$


In [21]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

print(np.linalg.solve(A, b))

[-4.   4.5]


# Estadística

In [22]:
x = np.array([1,2,3])

print(np.mean(x))

2.0
